# Generated by Django 5.0.4 on 2024-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=4)),
                ('al_counter', models.PositiveSmallIntegerField(default=0)),
                ('glass_counter', models.PositiveSmallIntegerField(default=0)),
                ('pvc_counter', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('S', 'Доставчик'), ('F', 'Фирма'), ('RC', 'Клиент на дребно')], max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(choices=[('A', 'Алуминий'), ('G', 'Стъклопакети'), ('P', 'PVC'), ('O', 'Поръчки'), ('M', 'Управител')], max_length=1)),
                ('order_type', models.CharField(choices=[('C', 'Каса'), ('B', 'Банка'), ('S', 'Продажба'), ('A', 'Поръчка Алуминий'), ('G', 'Поръчка Стъклопакети'), ('P', 'Поръчка PVC')], max_length=2)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('order', models.CharField(blank=True, max_length=11, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('partner', models.ForeignKey(default=1000, on_delete=models.SET(1000), related_name='records', to='records.partner')),
            ],
        ),
    ]
