# Generated by Django 5.0.4 on 2025-01-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='order_type',
            field=models.CharField(choices=[('C', 'Каса'), ('B', 'Банка'), ('S', 'Продажба'), ('A', 'Поръчка Алуминий'), ('G', 'Поръчка Стъклопакети'), ('P', 'Поръчка PVC')], max_length=2),
        ),
    ]
