# Generated by Django 5.0.4 on 2025-02-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_amount_alter_record_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='balance',
        ),
    ]
