from django.db import models


class GlassChoices(models.TextChoices):
    NONE = '', ''
    FOUR = '4', '4'
    K = 'K', 'K'
    MF = '4S', '4S'
    DELTA = 'делта', 'делта'
    KRIZET = 'кризет', 'кризет'
    MIRROR = 'огл', 'огл'
    MAT = 'мат', 'мат'
    GREY = 'сиво', 'сиво'
    GREEN = 'зелено', 'зелено'
    BRONZE = 'бронзе', 'бронзе'
    BLUE = 'синьо', 'синьо'
    GREY_STS = 'сиво_стс', 'сиво_стс'
    GREEN_STS = 'зел_стс', 'зел_стс'
    BRONZE_STS = 'бронзе_стс', 'бронзе_стс'
    BLUE_STS = 'синьо_стс', 'синьо_стс'
    FIVE = '5', '5'
    SIX = '6', '6'
    SIX_K = '6_К', '6_К'
    SIX_4S = '6_4S', '6_4S'
    SIX_GRAY = '6_сиво', '6_сиво'
    SIX_GREEN = '6_зел', '6_зел'
    SIX_BRONZE = '6_бронзе', '6_бронзе'
    SIX_BLUE = '6_синьо', '6_синьо'
    SIX_GRAY_STS = '6_сиво_стс', '6_сиво_стс'
    SIX_GREEN_STS = '6_зел_стс', '6_зел_стс'
    SIX_BRONZE_STS = '6_бронзе_стс', '6_бронзе_стс'
    SIX_BLUE_STS = '6_синьо_стс', '6_синьо_стс'
    EIGHT = '8', '8'
    EIGHT_MAT = '8_мат', '8_мат'
    TEN = '10', '10'
    TEN_MAT = '10_мат', '10_мат'
    TEN_GREY = '10_сиво', '10_сиво'
    THREE_THREE_ONE = '331', '331'
    FOUR_FOUR_ONE = '441', '441'
    FIFE_FIFE_ONE = '551', '551'
    FOUR_FOUR_ONE_MAT = '441_мат', '441_мат'
    FOUR_FOUR_ONE_GREY = '441_сиво', '441_сиво'
    FOUR_FOUR_ONE_BRONZE = '44_бронзе', '44_бронзе'


class ThicknessChoices(models.IntegerChoices):
    TWELVE = 12, '12'
    FOURTEEN = 14, '14'
    SIXTEEN = 16, '16'
    EIGHTEEN = 18, '18'
    TWENTY = 20, '20'
    TWENTY_TWO = 22, '22'
    TWENTY_FOUR = 24, '24'
    TWENTY_FIVE = 25, '25'
    TWENTY_SIX = 26, '26'
    TWENTY_SEVEN = 27, '27'
    TWENTY_EIGHT = 28, '28'
    THIRTY = 30, '30'
    THIRTY_TWO = 32, '32'
    THIRTY_FOUR = 34, '34'
    THIRTY_SIX = 36, '36'
    THIRTY_EIGHT = 38, '38'
    FORTY = '40', '40'
    FORTY_TWO = 42, '42'
    FORTY_FOUR = 44, '44'





