# Generated by Django 5.0.4 on 2025-01-06 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_glass', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('K', 'K'), ('4S', '4S')], max_length=12)),
                ('second_glass', models.CharField(blank=True, choices=[('4', '4'), ('5', '5'), ('6', '6'), ('K', 'K'), ('4S', '4S')], max_length=12, null=True)),
                ('third_glass', models.CharField(blank=True, choices=[('4', '4'), ('5', '5'), ('6', '6'), ('K', 'K'), ('4S', '4S')], max_length=12, null=True)),
                ('thickness', models.IntegerField(choices=[(12, '12'), (14, '14'), (16, '16'), (18, '18'), (20, '20'), (22, '22'), (24, '24')])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(3210)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(3210)])),
                ('number', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_for_working', models.BooleanField(default=False)),
                ('sent_for_working', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.record')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.partner')),
            ],
        ),
    ]
