# Generated by Django 5.0.4 on 2025-01-25 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_glasses_price_alter_glasses_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
