# Generated by Django 5.0.4 on 2025-01-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_alter_glasses_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glasses',
            old_name='order',
            new_name='record',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='partner',
        ),
    ]
