# Generated by Django 5.0.4 on 2025-02-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_rename_order_glasses_record_remove_glasses_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='sent_for_working',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
