# Generated by Django 5.0.4 on 2025-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0006_glasses_module_alter_glasses_first_glass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='supplement',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
